### ISSUE TITLE
Open-source License

### ISSUE THREAD

**Issue by fa-schwarz** [trevor-crypto/sgx-ra-tls-client#1]
Hey,
thanks for publishing this cool and very useful Java client for ra-TLS.
We are currently working on an open-source project and would be interested to link your client library.

Your project has *no* license at the moment, i.e., nobody is allowed to use it.
Can you please consider adding an open-source license to the project,  by adding a respective `LICENSE` file? :-)

Github has builtin support for adding all kind of open-source licenses, e.g., the `MIT` or `3-BSD` license.

Here is the Github documentation for it:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks for taking the time.

**Comment by trevor-crypto** [comment]
Hi @fa-schwarz. Nice to hear!

I will definitely add a license ASAP.

Also welcoming any improvements via PR.
